### ISSUE TITLE
Proxies written to file contain white spaces

### ISSUE THREAD

**Issue by Adrian201230** [Jojiv2/Scrappp#1]
When written to the file it contains a blank line each time
example:
103.141.12.161:1080

107.189.10.54:29198

46.101.5.73:45775

To fix it I changed the code of main for each proxytype to:
passwordhttp = 'http'
httpnew = httpget.text.replace("\n","") // this one being the extra line
httpfile = open(f"{passwordhttp}.txt", "a")
httpfile.write(f"{httpnew}")
httpfile.close()

In this way the proxies can be easily copied and placed in proxytesters.

**Comment by m0n3ef** [comment]
Thank you for the report and helping me improving this repo
appreciate it
im working on scrappp v2, fixed this one, the reason why this in the old versions because im giving scrappp v2 full focus
thank you <3
